### ISSUE TITLE
Videos don't play even in external player

### ISSUE THREAD

**Issue by jmaris** [LeonardLaszlo/popcorn-time-installation-guide-armv7#3]
I cannot seem to get videos to play, even in an external player, Is this still to do with missing codecs in nwjs ? 

It doesn't display any error, I have tried VLC and mplayer

**Comment by LeonardLaszlo** [comment]
what device do you use?

**Comment by jmaris** [comment]
I have a HP Chromebook 11. I get linux using Crouton

**Comment by LeonardLaszlo** [comment]
It doesn't work on chromebook. This installer is for ubuntu, it can work on other linux distribution, but I did not try it.

**Comment by jmaris** [comment]
Ok, Technically though, it is ubuntu (Running in a Chroot via crouton), I don't see what could be stopping this from working, the video decoding won't be hardware accelerated, however software accelerated video decoding should be possible.

**Comment by LeonardLaszlo** [comment]
Start Popcorn-Time from terminal and post the log!

**Comment by LeonardLaszlo** [comment]
I closed the issue because you did not reply in months.
