### ISSUE TITLE
Kodi not listed as player

### ISSUE THREAD

**Issue by mad-ady** [LeonardLaszlo/popcorn-time-installation-guide-armv7#4]
Hello,

I've followed your guide and installed PopcornTime on Odroid-C1. I can play content with the builtin player, but I'm trying to stream content to Kodi (which can use hardware decoding). The problem is - Kodi is not in the list of players.

I'm running on a odroid c1+, running HardKernel's official 14.04 image with Kodi 15.02 installed in /usr/local/lib/kodi.

I also tried option #2, but I see no setting under Popcorn-Time where you can set the port to stream to. It does open Kodi, but kodi complains that there are no more items to play in the playlist (most likely due to the wrong port).

Where would I set the port in PopcornTime? Maybe directly in a config file?

Thanks

**Comment by LeonardLaszlo** [comment]
OS crashes when I try to play something using KODI

**Comment by LeonardLaszlo** [comment]
OS crashes when I try to play something using KODI

**Comment by LeonardLaszlo** [comment]
Still not working

**Comment by mad-ady** [comment]
Could you point me to the place in settings where you set the streaming port for popcorn time? I can't find it even with advanced turned on...

**Comment by LeonardLaszlo** [comment]
I don't set the streaming port for popcorn time. I only added kodi as external player in the source code and rebuilt the project, but there is a problem when I run it on linux. On OS X it works well.

**Comment by LeonardLaszlo** [comment]
BTW the port can be set in the stream file as explained in the following tutorial: https://github.com/LeonardLaszlo/popcorn-time-building-guide-armv7/blob/master/KODI.md

**Comment by LeonardLaszlo** [comment]
The crash I experienced it seems to be related to the device I used for testing, an Odroid-U3. On Odroid-XU4 runs smoothly. I closed the thread with the latest commit. Please let me know if this commit solved your problem! O zii buna!

**Comment by mad-ady** [comment]
Yes, I confirm that it works and it plays through Kodi on an Odroid C1+. Thank you for your help
