### ISSUE TITLE
Unable to locate popcorn time folder on raspbian

### ISSUE THREAD

**Issue by lazarvgd** [LeonardLaszlo/popcorn-time-installation-guide-armv7#6]
Hi there,

I have cloned this project and followed installation guide. Unfortunately I cannot locate folder from where I can start popcorntime. Can you please help me to solve this issue?

thanks :)

**Comment by SvenVlieghe** [comment]
I'm using archLinux instead of raspbian, but here it installed in /root/.Popcorn-Time
Note that it's a hidden folder, so 'ls' wont do, try 'ls -a'
Good luck!

**Comment by LeonardLaszlo** [comment]
It is installed in the home directory of the user who runned the instalation script, under the .Popcorn-Time directory, which is hidden by default
